name: ga-linter
on: [push]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: npm install, build
      - run: make install
      - run: make lint
      # Install and build project
      